# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https: //aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: github
      name: ivesma/AzPipelineTemplates
      ref: v0.0.1
      endpoint: svc_pipeline_templates

steps:
- template: steps/step-Search-Files-Path.yml@templates
  parameters:
    CopyToFolder: false
    FileNames:
    - Name: 'AzPipelineDocWriter.psd1'
      VarName: 'moduleDef.File.Path'
    - Name: 'AzPipelineDocWriter.psm1'
      VarName: 'module.File.Path'
    - Name: 'AzPipelineDocWriter.pssettings'
      VarName: 'module.Settings.Path'
    ReturnFullPath: false
    RootFolder: $(Build.SourcesDirectory)
    TargetFolder: $(build.artifactstagingdirectory)
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https: //aka.ms/yaml
    echo "Module Definition Path: $(moduleDef.File.Path)"
    echo "Module Path: $(module.File.Path)"
    echo "Module Settings Path: $(module.Settings.Path)"
  displayName: 'Run a multi-line script'
